# version: "3.3"
# services:
#   web:
#     build: .
#     ports:
#       - 80:80
#     volumes: 
#       - .:/app 

version: "3.4"
services:
  client:
    # image: client
    # restart: on-failure
    build: .
      # context: ./client
      # dockerfile: Dockerfile.dev
    ports:
      - 5173:5173
      - 24678:24678
    volumes:
      - ./:/app
      - /app/node_modules